BEGIN TRANSACTION;
CREATE TABLE "Order" (
	`orderId`	INTEGER PRIMARY KEY AUTOINCREMENT,
	`paymentId`	INTEGER,
	`customerId`	INTEGER,
	`isPaid`	INTEGER NOT NULL DEFAULT 0
);
INSERT INTO `Order` VALUES (1,1,1,1);
INSERT INTO `Order` VALUES (2,2,1,1);
INSERT INTO `Order` VALUES (3,3,1,1);
INSERT INTO `Order` VALUES (4,4,2,1);
INSERT INTO `Order` VALUES (5,8,3,1);
INSERT INTO `Order` VALUES (6,9,4,1);
INSERT INTO `Order` VALUES (7,11,5,1);
INSERT INTO `Order` VALUES (8,14,6,0);
COMMIT;
